### ISSUE TITLE
Option to disable border.

### ISSUE THREAD

**Issue by Sourav2005** [var512/mpv-scripts#1]
It is not exactly an issue but more of a feature request. I unfortunately do not know lua so I could not do this on my own,

Here is a command I found on reddit: 

```
mpv --ontop --no-border --autofit=384x216 --geometry=99%:2% [file]
```

Can one achieve the same thing with your script? Since I have enabled save-position-on-quit enabled in my mpv.conf it always resets the aspect ratio. I also tried using toggle-pip.conf but it still resets the aspect ratio.

So I please ask you if I can make your script do what the above script does. Thank you very much in advance.

**Comment by var512** [comment]
I haven't touched that script in a long time but I remember finding a lot of edge cases. That's one of the reasons it restores some properties, also to make it compatible with other scripts. I'd rather not change it again as I'm sure it will only add bugs.

If `autofit` and `geometry` are more stable now it might make sense to start a new version of that script. Your issue happens when you toggle the script and the window doesn't go back to what mpv originally calculated? I vaguely remember an mpv issue about `save-position-on-quit` and saving window sizes.
